/**
 * RM2PT Generator Runtime
 * generated by RM2PT v1.3.0
 */
package com.rm2pt.generator.golangclassgenerate;

import com.google.common.collect.Iterables;
import java.util.ArrayList;
import net.mydreamy.requirementmodel.rEMODEL.Entity;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

@SuppressWarnings("all")
public class CodeGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    System.out.println("hello, goen!!!");
    ArrayList<Entity> entities = new ArrayList<Entity>();
    Iterable<Entity> ite = Iterables.<Entity>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Entity.class);
    for (final Entity e : ite) {
      {
        System.out.println(e);
        entities.add(e);
      }
    }
    System.out.println("hello, goen!!!");
    ContractGenerator.generate(resource);
  }
}
